### ISSUE TITLE
Website notifications get rendered double

### ISSUE THREAD

**Issue by klappradla** [klappradla/im_graetzl#100]
Each new notification is displayed double in the notification dropdown. For each activity, a notification record is created twice.

See example:
![screen shot 2015-09-16 at 13 03 39](https://cloud.githubusercontent.com/assets/3491815/9903199/b7068492-5c74-11e5-8f4f-ffd44983ae23.png)

**Comment by tawan** [comment]
It seems that in development mode, after changes to the code, the [Observer](https://github.com/klappradla/im_graetzl/blob/master/app/models/notification.rb#L98) gets registered an additional time.
