### ISSUE TITLE
Prevent notification center from repopulating when (re-)enable notification type

### ISSUE THREAD

**Issue by klappradla** [klappradla/im_graetzl#104]
Prevent notification center from re-populating with unseen notification when a user enables or reenables a type of notification. In the current setup, the user is confronted with a huge queue of unseen notifications when toggling his/her settings.

Quick solutions could be to:
* mark notifications as seen (might conflict with email)
* prevent notification from being created, resembling [this old solution](https://github.com/klappradla/im_graetzl/blob/master/app/models/notification.rb#L83)

**Comment by tawan** [comment]
@klappradla I can remember now why I commented out the check. Because of a potential mail notification I had to create the record, but then it would show up if the user enables the website type afterwards. I added a flag column to the notifications table. Not the most elegant solution.
