### ISSUE TITLE
Refile stream images from S3 not working in IE

### ISSUE THREAD

**Issue by klappradla** [klappradla/im_graetzl#11]
Via [Refile](https://github.com/refile/refile) hochgeladene und auf Amazon S3 gespeicherte Bilder werden im IE (sogar 11) nicht angezeigt bzw. können nicht gestreamt werden.

Beispiel:
![ie_img_prob](https://cloud.githubusercontent.com/assets/3491815/8718459/dd0bee62-2ba4-11e5-86c9-70ba98d8f491.PNG)

Entspricht [dieser Issue](https://github.com/refile/refile/issues/272) bei Refile.

Lösungsmöglichkeiten:

1. Filename in DB speichern
2. Filetyp spezifizieren (unflexible)
3. Content Type in DB speichern

Variante 3 ist am flexibelsten. Umsetzbar z.B. mit Helper wie [hier](https://github.com/refile/refile/issues/92).

**Comment by klappradla** [comment]
@peckomingo Content Type für Bilder sollte jetzt sowohl lokal als auch auf S3 da sein.

Bitte kurz im IE probieren (lokal und staging) ob jetzt alles sichtbar ist.

**Comment by peckomingo** [comment]
Jo Bilder funktionieren nun in IE. Super!
