### ISSUE TITLE
States / make as :deleted

### ISSUE THREAD

**Issue by klappradla** [klappradla/im_graetzl#12]
@tawan Ich werde für die Locations eine State Machine brauchen (gem Recommendations welcome). Falls Du im Zuge der Notifications für Meetings und GoingTos :deleted-flags setzen willst und [paranoia](https://github.com/radar/paranoia) noch nicht eingebunden hast, wäre das evtl. auch über State Machines gut lösbar.

**Comment by klappradla** [comment]
Aktueller Gemkandidat: [aasm](https://github.com/aasm/aasm)

**Comment by tawan** [comment]
Hi @klappradla . Ich habe mit [diesem Gem](https://github.com/pluginaweek/state_machine) gearbeitet und das hat ganz gut funktioniert. Auf keinen Fall würde ich [workflow](https://github.com/geekq/workflow) benutzen, weil da habe ich schlechte Erfahrungen gemacht, obwohl das auch wieder einige Jahre her ist. Prinzipiell würde ich das verwenden was weniger kann / komplex ist. Natürlich muss es den use case abdecken

Aber du hast recht, deleted flags sollten wir eventuell dann mit dieser jeweiligen state_machine Lösung umsetzen.

LG

**Comment by klappradla** [comment]
@tawan [state_machine](https://github.com/pluginaweek/state_machine) und [aasm](https://github.com/aasm/aasm) sind sich in Funktion und Handhabung recht ähnlich. State_machine scheint aber ein bisschen outdated (letzter Commit vor 2 Jahren) und damit weniger Rails 4.2 ready als aasm (letzter Commit vor 1 Monat, Update auf 4.2) zu sein.

Nutze jetzt aasm, funktioniert soweit auch sehr gut. Für deleted flags ist es aber eigentlich fast zu overkill, eine State Machine ins Model einzubauen merke ich nun. Deshalb kannst Du für diese Funktion gern auch bei [paranoia](https://github.com/radar/paranoia) bleiben. Scheint mir in dem Fall dann doch die cleanere und leightweightere (fällt mir kein Deutsches Wort dazu ein) Solution zu sein.
