### ISSUE TITLE
ActiveRecord::RecordNotFound when meeting changes Grätzl

### ISSUE THREAD

**Issue by tawan** [klappradla/im_graetzl#20]
<img width="1116" alt="screen shot 2015-07-26 at 14 00 57" src="https://cloud.githubusercontent.com/assets/6555/8893784/dc4f6984-339e-11e5-8324-51bc5c07085f.png">

As a user I attend a meeting. The initiator changes the address of the meeting, but the address belongs to another Grätzl. This error is the result.

**Comment by tawan** [comment]
Seen in version 63cf07c

**Comment by klappradla** [comment]
Thanx @tawan !

Which scenario? User views meeting, initiator updates address, user refreshes page? <- only way I can reproduce the error.

Origin: changing the address changes the associated graetzl and therefore changes the meeting's url from 'old_graetzl/meeting_slug' to 'new_graetzl/meeting_slug'. (For SEO reasons and to not confuse user with displaying them meeting in old_graetzl when they actually take place somewhere else.)

Possible solution: extend [set_meeting](https://github.com/klappradla/im_graetzl/blob/master/app/controllers/meetings_controller.rb#L98) to in case of graetzl <-> meeting.graetzl missmatch redirect to meeting in meeting.graetzl.

**Comment by klappradla** [comment]
Note to self: reuse pattern for Locations.
