### ISSUE TITLE
Refactor GoingTo Roles to use Enum Hash

### ISSUE THREAD

**Issue by klappradla** [klappradla/im_graetzl#36]
Refactor GoingTo Roles to use enum hash. Simplify rights-management.

**Comment by klappradla** [comment]
Reason: keep flexibility to in future have multiple initators / multiple user roles in attending meetings.

@tawan Betrifft minimal auch die Notifications. Wenn ich die Tests grün habe und die Partials durchgeschaut habe, sollte es aber passen oder?

**Comment by tawan** [comment]
@klappradla Hi, Ja ich denke mit grünen Tests sollte es passen
