### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by peckomingo** [klappradla/im_graetzl#6]
./spec/features/registrations_spec.rb:25 # Registrations register new user find graetzl searc
h address with single result forwards to details form

./spec/features/registrations_spec.rb:38 # Registrations register new user find graetzl searc
h address with multiple results shows options to choose graetzl and forwards to details from

./spec/features/registrations_spec.rb:56 # Registrations register new user find graetzl searc
h address with no result lets choose district and graetzl

./spec/views/meetings/show.html.erb_spec.rb:47 # meetings/show header section date when date
not set displays empty calendar icon

./spec/views/meetings/show.html.erb_spec.rb:70 # meetings/show header section date when date
set displays date in calendar icon

./spec/views/meetings/show.html.erb_spec.rb:89 # meetings/show header section address when ad
dress not set displays map icon

**Comment by peckomingo** [comment]
./spec/features/registrations_spec.rb:38 # Registrations register new user find graetzl searc
h address with multiple results shows options to choose graetzl and forwards to details from

**Comment by peckomingo** [comment]
./spec/features/registrations_spec.rb:56 # Registrations register new user find graetzl searc
h address with no result lets choose district and graetzl

**Comment by peckomingo** [comment]
./spec/views/meetings/show.html.erb_spec.rb:47 # meetings/show header section date when date
not set displays empty calendar icon

**Comment by peckomingo** [comment]
./spec/views/meetings/show.html.erb_spec.rb:70 # meetings/show header section date when date
set displays date in calendar icon

**Comment by peckomingo** [comment]
./spec/views/meetings/show.html.erb_spec.rb:89 # meetings/show header section address when ad
dress not set displays map icon

**Comment by klappradla** [comment]
@peckomingo Die [registration feature specs](https://github.com/klappradla/im_graetzl/blob/master/spec/features/registrations_spec.rb) failen bei Dir lokal wohl weil Dir [PhantomJS](http://phantomjs.org/) fehlt. Steht im Readme, werde das dort auch nochmal verlinken.

Sollten dann problemlos laufen, die registration feature specs.
