### ISSUE TITLE
Visually mark :readonly input fields in meeting form

### ISSUE THREAD

**Issue by klappradla** [klappradla/im_graetzl#62]
Form inputs marked as `readonly=true` or `readonly=readonly` are not editable for users but still passed to the server on form submit (unlike inputs marked as disabled). In the current form styling, the uneditable character of a readonly input is not visually recognisable for the user.

One example for such an input: the [address field](https://github.com/klappradla/im_graetzl/blob/master/app/views/meetings/_form.html.erb#L46) in the meeting form.
Use case: *User inits a meeting from the button on a location page (address is already determined).*

**Comment by peckomingo** [comment]
fixed with next
