### ISSUE TITLE
Link to post pages from stream items

### ISSUE THREAD

**Issue by klappradla** [klappradla/im_graetzl#81]
Temporary (maybe final) solution: textual post content displayed as link *(see screenshot)*
![screen shot 2015-09-09 at 15 24 12](https://cloud.githubusercontent.com/assets/3491815/9762951/113b9d76-5707-11e5-92e4-9a32a347d94c.png)

Problems:
1. Might not be intuitiv.
2. Underlined content has weird look.

**Comment by peckomingo** [comment]
should be fixed
